/*
 * Decompiled with CFR 0.152.
 */
package main;

import entity.Entity;
import entity.NPC_BigRock;
import entity.NPC_BlackSmith;
import entity.NPC_Dad;
import entity.NPC_Garther;
import entity.NPC_Merchant;
import entity.NPC_Mom;
import entity.NPC_OldMan;
import java.util.Objects;
import main.GamePanel;
import monsters.MON_Bat;
import monsters.MON_DungeonOrc;
import monsters.MON_GreenSlime;
import monsters.MON_Orc;
import monsters.MON_RedSlime;
import monsters.MON_SkeletonLord;
import monsters.MON_SlimeBoss;
import objects.OBJ_Axe;
import objects.OBJ_Bag;
import objects.OBJ_Chest;
import objects.OBJ_Door;
import objects.OBJ_Door_Iron;
import objects.OBJ_Key;
import objects.OBJ_Pickaxe;
import objects.OBJ_Potion_Red;
import objects.OBJ_Shield_Wood;
import objects.OBJ_Sugar;
import objects.OBJ_Sword_Normal;
import objects.OBJ_Tent;
import objects.OBJ_Torch;
import tile_interactive.IT_Barrier;
import tile_interactive.IT_Bed;
import tile_interactive.IT_Bookshelf;
import tile_interactive.IT_Chair;
import tile_interactive.IT_Couch;
import tile_interactive.IT_DestructibleWall;
import tile_interactive.IT_DinningTable;
import tile_interactive.IT_Drawer;
import tile_interactive.IT_DryTree;
import tile_interactive.IT_House;
import tile_interactive.IT_Kitchen;
import tile_interactive.IT_Log;
import tile_interactive.IT_MetalPlate;
import tile_interactive.IT_Rug;
import tile_interactive.IT_Torch;
import tile_interactive.IT_Village;
import tile_interactive.InteractiveTile;

public class AssetSetter {
    GamePanel gp;

    public AssetSetter(GamePanel gamePanel) {
        this.gp = gamePanel;
    }

    public void setObject() {
        int slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].setLoot(new OBJ_Sword_Normal(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldX = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldY = this.gp.tileSize * 42;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldY = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldX = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldY = this.gp.tileSize * 33;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.obj[3][slotIndex].worldY = this.gp.tileSize * 6;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].setLoot(new OBJ_Shield_Wood(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].worldY = this.gp.tileSize * 18;
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].worldX = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].setLoot(new OBJ_Torch(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].worldX = this.gp.tileSize * 34;
        Objects.requireNonNull(this.gp);
        this.gp.obj[4][slotIndex].worldY = this.gp.tileSize * 14;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldY = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldX = this.gp.tileSize * 33;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldY = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldX = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldX = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldY = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].setLoot(new OBJ_Tent(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldX = this.gp.tileSize * 40;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldY = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldX = this.gp.tileSize * 15;
        Objects.requireNonNull(this.gp);
        this.gp.obj[8][slotIndex].worldY = this.gp.tileSize * 33;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex] = new OBJ_Door(this.gp, 3);
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldX = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldY = this.gp.tileSize * 6;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].setLoot(new OBJ_Torch(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldY = this.gp.tileSize * 29;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldY = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.obj[10][slotIndex].worldY = this.gp.tileSize * 13;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[7][slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[7][slotIndex].setLoot(new OBJ_Axe(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[7][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.obj[7][slotIndex].worldY = this.gp.tileSize * 10;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].setLoot(new OBJ_Pickaxe(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldX = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldY = this.gp.tileSize * 40;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldY = this.gp.tileSize * 17;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].setLoot(new OBJ_Torch(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldY = this.gp.tileSize * 17;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldX = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldY = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].setLoot(new OBJ_Torch(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldX = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldY = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].setLoot(new OBJ_Torch(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldX = this.gp.tileSize * 42;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldY = this.gp.tileSize * 6;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][++slotIndex] = new OBJ_Door_Iron(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldX = this.gp.tileSize * 17;
        Objects.requireNonNull(this.gp);
        this.gp.obj[11][slotIndex].worldY = this.gp.tileSize * 22;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex] = new OBJ_Door_Iron(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 7;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Door(this.gp, 2);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Door(this.gp, 2);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Door(this.gp, 2);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 34;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 28;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Torch(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 33;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Key(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Key(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Key(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 7;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 8;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Key(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 7;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 8;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].setLoot(new OBJ_Potion_Red(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldX = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.obj[12][slotIndex].worldY = this.gp.tileSize * 22;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][slotIndex].setLoot(new OBJ_Sugar(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][slotIndex].worldX = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][slotIndex].worldY = this.gp.tileSize * 6;
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][++slotIndex] = new OBJ_Chest(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][slotIndex].setLoot(new OBJ_Bag(this.gp));
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][slotIndex].worldX = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.obj[13][slotIndex].worldY = this.gp.tileSize * 6;
        ++slotIndex;
    }

    public void setNPC() {
        int slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.npc[1][slotIndex] = new NPC_Mom(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[1][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.npc[1][slotIndex].worldY = this.gp.tileSize * 18 + 5;
        Objects.requireNonNull(this.gp);
        this.gp.npc[1][++slotIndex] = new NPC_Dad(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[1][slotIndex].worldX = this.gp.tileSize * 20 - 25;
        Objects.requireNonNull(this.gp);
        this.gp.npc[1][slotIndex].worldY = this.gp.tileSize * 18 + 4;
        ++slotIndex;
        slotIndex = 0;
        if (!this.gp.orcRobbedPlayer) {
            Objects.requireNonNull(this.gp);
            this.gp.npc[5][slotIndex] = new NPC_OldMan(this.gp);
            Objects.requireNonNull(this.gp);
            this.gp.npc[5][slotIndex].worldX = this.gp.tileSize * 34;
            Objects.requireNonNull(this.gp);
            this.gp.npc[5][slotIndex].worldY = this.gp.tileSize * 24;
            ++slotIndex;
        }
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex] = new NPC_BlackSmith(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldX = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldY = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][++slotIndex] = new NPC_Garther(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldX = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][++slotIndex] = new NPC_BlackSmith(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldX = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldY = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][++slotIndex] = new NPC_Garther(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldX = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][++slotIndex] = new NPC_Garther(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldX = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.npc[5][slotIndex].worldY = this.gp.tileSize * 28;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.npc[6][slotIndex] = new NPC_Merchant(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[6][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.npc[6][slotIndex].worldY = this.gp.tileSize * 7;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.npc[7][slotIndex] = new NPC_OldMan(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[7][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.npc[7][slotIndex].worldY = this.gp.tileSize * 12;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][slotIndex] = new NPC_BigRock(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][slotIndex].worldX = this.gp.tileSize * 7;
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][slotIndex].worldY = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][++slotIndex] = new NPC_BigRock(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][slotIndex].worldX = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][slotIndex].worldY = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][++slotIndex] = new NPC_BigRock(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][slotIndex].worldX = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.npc[11][slotIndex].worldY = this.gp.tileSize * 7;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][slotIndex] = new NPC_BigRock(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][slotIndex].worldX = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][slotIndex].worldY = this.gp.tileSize * 15;
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][++slotIndex] = new NPC_BigRock(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][slotIndex].worldX = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][++slotIndex] = new NPC_BigRock(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][slotIndex].worldX = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.npc[12][slotIndex].worldY = this.gp.tileSize * 11;
        ++slotIndex;
    }

    public void setSlimeBoss() {
        int slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[9][slotIndex] = new MON_SlimeBoss(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[9][slotIndex].worldX = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[9][slotIndex].worldY = this.gp.tileSize * 20;
        ++slotIndex;
    }

    public void setSkeletonLord() {
        int slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[13][slotIndex] = new MON_SkeletonLord(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[13][slotIndex].worldX = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.monster[13][slotIndex].worldY = this.gp.tileSize * 16;
        ++slotIndex;
    }

    public void setMonster() {
        int slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 15;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 15;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 33;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 34;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldX = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.monster[3][slotIndex].worldY = this.gp.tileSize * 27;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 31;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[4][slotIndex].worldY = this.gp.tileSize * 22;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 28;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 23;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 28;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 28;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 31;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[8][slotIndex].worldY = this.gp.tileSize * 36;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 34;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 34;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 34;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 34;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_RedSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 35;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_GreenSlime(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 37;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 20;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 20;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][++slotIndex] = new MON_Orc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldX = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.monster[10][slotIndex].worldY = this.gp.tileSize * 16;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 40;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 42;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 17;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 40;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 29;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 29;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 40;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 15;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 36;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 15;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 29;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 23;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[11][slotIndex].worldY = this.gp.tileSize * 10;
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 27;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 30;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 29;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 26;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 39;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 40;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 38;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 15;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 17;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 32;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 17;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 20;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_Bat(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 41;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 11;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 12;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 19;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 20;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 13;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 14;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 16;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 17;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 21;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 22;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 9;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 24;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 25;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 37;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 10;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][++slotIndex] = new MON_DungeonOrc(this.gp);
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldX = this.gp.tileSize * 40;
        Objects.requireNonNull(this.gp);
        this.gp.monster[12][slotIndex].worldY = this.gp.tileSize * 10;
        ++slotIndex;
    }

    public void setInteractiveTile() {
        int slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[0][slotIndex] = new IT_Bed(this.gp, 15, 25);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[0][++slotIndex] = new IT_Drawer(this.gp, 17, 25);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[0][++slotIndex] = new IT_Bookshelf(this.gp, 22, 22);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[1][slotIndex] = new IT_Kitchen(this.gp, 12, 18);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[1][++slotIndex] = new IT_Couch(this.gp, 20, 25);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[1][++slotIndex] = new IT_Chair(this.gp, 18, 20, "Up");
        Objects.requireNonNull(this.gp);
        this.gp.iTile[1][++slotIndex] = new IT_Rug(this.gp, 18, 25);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[1][++slotIndex] = new IT_DinningTable(this.gp, 19, 20);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[1][++slotIndex] = new IT_Barrier(this.gp, 27, 29, "talk_to_mom", 1);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[2][slotIndex] = new IT_House(this.gp, 13, 31);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[3][slotIndex] = new IT_DryTree(this.gp, 36, 18);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[3][++slotIndex] = new IT_DryTree(this.gp, 33, 35);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[3][++slotIndex] = new IT_Log(this.gp, 38, 37);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[4][slotIndex] = new IT_Village(this.gp, 31, 29, 1);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[4][++slotIndex] = new IT_Village(this.gp, 38, 28, 2);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[4][++slotIndex] = new IT_Village(this.gp, 31, 39, 5);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[4][++slotIndex] = new IT_Village(this.gp, 42, 39, 4);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[4][++slotIndex] = new IT_DryTree(this.gp, 10, 37);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][slotIndex] = new IT_Village(this.gp, 11, 20, 3);
        ++slotIndex;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][slotIndex] = new IT_Village(this.gp, 0, 19, 1);
        ++slotIndex;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][slotIndex] = new IT_Village(this.gp, 19, 10, 2);
        ++slotIndex;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][slotIndex] = new IT_Village(this.gp, 23, 37, 4);
        ++slotIndex;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][slotIndex] = new IT_Village(this.gp, 30, 11, 6);
        ++slotIndex;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][slotIndex] = new IT_Village(this.gp, 36, 11, 1);
        ++slotIndex;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][slotIndex] = new IT_Village(this.gp, 31, 37, 5);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][++slotIndex] = new IT_DryTree(this.gp, 15, 12);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][++slotIndex] = new IT_DryTree(this.gp, 15, 11);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[5][++slotIndex] = new IT_DryTree(this.gp, 15, 10);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[7][slotIndex] = new IT_Bed(this.gp, 9, 10);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][slotIndex] = new IT_MetalPlate(this.gp, 7, 17);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_MetalPlate(this.gp, 13, 24);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_MetalPlate(this.gp, 21, 19);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_Torch(this.gp, 19, 22, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_Torch(this.gp, 16, 22, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_Torch(this.gp, 23, 7, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_Torch(this.gp, 10, 6, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_Torch(this.gp, 14, 6, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 17, 36);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 18, 36);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 17, 35);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 18, 35);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 17, 34);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 18, 34);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 17, 33);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 18, 33);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 17, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 18, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 17, 31);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 18, 31);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 18, 30);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 23, 28);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 23, 27);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 24, 28);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 26, 29);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 26, 30);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 26, 31);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 26, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 30, 27);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 31, 27);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 31, 28);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 7, 26);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 7, 25);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 8, 26);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 7, 22);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 8, 22);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 38, 21);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 38, 22);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 39, 21);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 39, 22);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 39, 20);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 36, 11);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 37, 11);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[11][++slotIndex] = new IT_DestructibleWall(this.gp, 36, 10);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][slotIndex] = new IT_MetalPlate(this.gp, 43, 24);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_MetalPlate(this.gp, 21, 43);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_MetalPlate(this.gp, 7, 6);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_Torch(this.gp, 29, 22, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_Torch(this.gp, 32, 22, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_Torch(this.gp, 37, 7, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_Torch(this.gp, 40, 7, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 30, 37);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 31, 37);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 30, 36);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 31, 36);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 30, 35);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 25, 28);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 25, 29);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 36, 28);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 36, 29);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 41, 31);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 41, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 42, 31);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 42, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 41, 19);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 41, 20);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 41, 21);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 12, 31);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 12, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 11, 31);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 11, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 10, 32);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 15, 24);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 15, 25);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 14, 24);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 14, 25);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 7, 18);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 8, 18);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 7, 17);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 8, 17);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 28, 7);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 28, 8);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 10, 6);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 10, 7);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 9, 7);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[12][++slotIndex] = new IT_DestructibleWall(this.gp, 9, 6);
        ++slotIndex;
        slotIndex = 0;
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][slotIndex] = new IT_Torch(this.gp, 24, 33, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Torch(this.gp, 27, 33, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Torch(this.gp, 25, 4, this.gp.environmentLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Torch(this.gp, 21, 27, this.gp.bossLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Torch(this.gp, 30, 27, this.gp.bossLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Torch(this.gp, 21, 17, this.gp.bossLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Torch(this.gp, 30, 17, this.gp.bossLight);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Barrier(this.gp, 25, 31, "skeleton_lord", 1);
        Objects.requireNonNull(this.gp);
        this.gp.iTile[13][++slotIndex] = new IT_Barrier(this.gp, 26, 31, "skeleton_lord", 1);
        ++slotIndex;
    }
}
